name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  luajit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install luajit
      run: sudo apt-get install luajit

    - name: AvlTree test
      run: |
        cd sublua/test
        luajit avltree_basic.lua
        cd ../../

    - name: SegTree test
      run: |
        cd sublua/test
        luajit segtree_basic.lua
        cd ../../

    - name: MPM test
      run: |
        cd sublua/test
        luajit mpm_basic.lua
        cd ../../

    - name: MinCostFlow test
      run: |
        cd sublua/test
        luajit mincostflow_basic.lua
        cd ../../

    - name: Lazy SegTree test
      run: |
        cd sublua/test
        luajit lazyseg_basic.lua
        cd ../../

    - name: ABmatch test
      run: |
        cd sublua/test
        luajit abmatch_basic.lua
        cd ../../

    - name: TFDP test
      run: |
        cd sublua/test
        luajit tfdp_basic.lua
        cd ../../
