name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  luajit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install luajit
      run: sudo apt-get install luajit

    - name: AvlTree test
      run: |
        cd sublua/test
        luajit avltree_arc074d.lua
